In [1]:
import pandas as pd
import numpy as np

In [5]:
my_arr=np.arange(100000)
my_arr

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [6]:
my_list=list(range(100000))

In [7]:
%time for _ in range(10): myarr2=my_arr*2

Wall time: 2 ms


In [8]:
%time for _ in range(10): mylist=[x*2 for x in my_list]

Wall time: 185 ms


In [9]:
data=np.random.randn(2,3)


In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [13]:
data2=[[1,2,3,4],[4,5,6,7]]
arr2=np.array(data2)
arr2[0]

array([1, 2, 3, 4])

In [15]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
a=np.full([5,8],8)

In [17]:
a

array([[8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8]])

In [18]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [19]:
a=np.empty((2,3,4))

In [20]:
a

array([[[1.37231114e-311, 1.37231107e-311, 1.37231107e-311,
         1.37231108e-311],
        [1.37231110e-311, 1.37231100e-311, 1.37231100e-311,
         1.37231100e-311],
        [1.37231110e-311, 1.37231102e-311, 1.37231102e-311,
         1.37231102e-311]],

       [[1.37231102e-311, 1.37231102e-311, 1.37231102e-311,
         1.37231102e-311],
        [1.37231102e-311, 1.37231102e-311, 1.37231102e-311,
         1.37231102e-311],
        [1.37231102e-311, 1.37231102e-311, 1.37231102e-311,
         1.37231102e-311]]])

In [21]:
names=np.array(['Bob','Joe','will','Bob','will','Joe','Joe'])
data=np.random.randn(7,4)
data[names=='Bob']

array([[ 0.06151653,  0.70201958, -0.41811675,  0.10623964],
       [ 2.16577546, -0.78688311, -1.11551164, -0.0910465 ]])